name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "pnpm/action-setup@v2.2.3"
        with:
          version: "latest"
          run_install: true
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm test
